/**** Target : MySQL ****/

DROP TABLE IF EXISTS INTERNS;

CREATE TABLE INTERNS(
	ID INT NOT NULL AUTO_INCREMENT,
	LASTNAME VARCHAR(25),
	FIRSTNAME VARCHAR(25),
	EMAIL VARCHAR(25),
    PRIMARY KEY (ID)
);

INSERT INTO INTERNS(LASTNAME,FIRSTNAME,EMAIL) VALUES
('Bond','James','jbond@gmail.com');